MOVE_LIST = [
    {"name": "Rope", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "High knees", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "Jacks", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "Boxer shuffle", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "Invisible jump rope", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "PVC twists", "quietable": 1, "bag": 0, "pvc": 1, "reversible":0, "opener":1},
    {"name": "FIREFIGHTER CARRY twists", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":1},
    {"name": "PVC slips", "quietable": 1, "bag": 0, "pvc": 1, "reversible":0, "opener":0},

    {"name": "Pushups", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "Wide pushups", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":0},
    {"name": "Diamond pushups", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":0},
    {"name": "Hindu pushups", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":0},
    {"name": "Dive-bomber pushups", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":0},
    {"name": "SPEAR pushup sequence", "quietable": 1, "bag": 0, "pvc": 0, "reversible":0, "opener":0},
    {"name": "Box dips", "quietable": 1, "bag": 0, "box": 1, "reversible":0, "opener":0},

    {"name": "Squats", "quietable": 1, "bag": 0, "reversible":0, "opener":1},
    {"name": "Squat hold", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Pistol squats", "quietable": 1, "bag": 0, "reversible":1, "opener":0},
    {"name": "Squat jumps", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Tuck jumps", "quietable": 1, "bag": 0, "reversible":0, "opener":0},

    {"name": "Forward lunge", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "FIREFIGHTER CARRY Forward lunge", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Forward lunge with twist", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "MED BALL Forward lunge with twist", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Backward lunge", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "FIREFIGHTER CARRY Backward lunge", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Backward lunge with twist", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "MED BALL Backward lunge with twist", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Twisting lunge", "quietable": 1, "bag": 0, "reversible":0, "opener":0},

    {"name": "Reaching crunches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Feet-raised crunches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Candlestick crunches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Leg lifts", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Long-arm crunches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Alternating precision SPEAR crunches", "quietable": 1, "ground": 1, "reversible":0, "opener":0},
    {"name": "Bicycle", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":1},
    {"name": "X-ups", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "V-ups", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Spiderman crunches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "SPEAR situps", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},

    {"name": "Mountain climbers", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":1},
    {"name": "Cross-body mountain climbers", "quietable": 1, "ground":1, "bag": 0, "reversible":0, "opener":0},
    {"name": "SPEAR mountain climbers", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Boat extensions", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Russian twists", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Flutter kicks", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Heel touches", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Palm strike situps", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},

    {"name": "Extended plank", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":1},
    {"name": "Forearm plank", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":1},
    {"name": "Rotating plank", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},

    {"name": "Calf raises", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "FIREFIGHTER CARRY Calf raises", "quietable": 1, "bag": 0, "reversible":0, "opener":0},
    {"name": "Bear-crab roll", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Hip-outs", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Spiderman lunges", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Upas", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Butt bridges", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    {"name": "Candlesticks", "quietable": 1, "bag": 0, "ground":1, "reversible":0, "opener":0},
    
    {"name": "Jab", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Double jab", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Cross", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead upper", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear upper", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Clinch Lead knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Ref 1 Lead knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "MED BALL Lead knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Clinch Rear knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Ref 1 Rear knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "MED BALL Rear knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead elbow", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear elbow", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Lead knife hands", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear knife hands", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead ridge hands", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear ridge hands", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Standing switch knees", "quietable": 1, "bag": 1, "reversible":0},
    {"name": "Clinch Switch knees", "quietable": 1, "bag": 1, "reversible":0},
    {"name": "MED BALL Switch knees", "quietable": 1, "bag": 1, "reversible":0},
    
    {"name": "Dual hooks", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Hook, cross, hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Cross, hook, cross", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Slipping jab, low hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Slipping cross, low hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, rear elbow", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Overhand, uppercut, overhand", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "High hook, low hook, high hook", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear upper, hook, cross", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, slipping jab, cross, hook, cross, takedown", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, slipping cross, hook, cross, hook, takedown", "quietable": 1, "bag": 1, "reversible":1},
    
    {"name": "Jab, cross, liver shot, lead hook, rear elbow", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, spleen shot, lead hook, rear elbow", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Double jab, spleen shot, rear upper", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Double jab, liver shot, rear upper", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead hook, elbow, liver shot, rear knee", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead hook, elbow, spleen shot, rear knee", "quietable": 1, "bag": 1, "reversible":1},
    
    {"name": "Jab, cross, sprawl", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, hook, sprawl", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Jab, cross, hook, hook, sprawl", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Side kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Inverted Side kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Side kick shuffle phase 1", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Side kick shuffle phase 2", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Side kick shuffle phase 3", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Side kick shuffle phase 4", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Rear kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Hook kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Direct hook kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Wheel kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Inverted Wheel kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Wheel kick shuffle phase 1", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Wheel kick shuffle phase 2", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Wheel kick shuffle phase 3", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Wheel kick shuffle phase 4", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Spinning wheel kick phase 1", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Spinning wheel kick phase 2", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Spinning side kick phase 1", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Spinning side kick phase 2", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Crossing wheel kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Crossing rear kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Crossing side kick", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Lead roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "MED BALL Lead roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Rear roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "MED BALL Rear roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Lead x-axis shin kick", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Rear x-axis shin kick", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Lead groin kick", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Rear groin kick", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Rear front kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Lead front kick", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Lead groin kick, jab, cross", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Lead front kick, jab, cross", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Snap kick, rear kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Snap kick, wheel kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Snap kick, side kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Snap kick, hook kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Snap kick, side kick, rear kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "Low wheel kick, high wheel kick", "quietable": 1, "bag": 1, "reversible":1},
    {"name": "High wheel kick, low wheel kick", "quietable": 1, "bag": 1, "reversible":1},

    {"name": "Low roundhouse, mid roundhouse, high roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "MED BALL Low roundhouse, mid roundhouse, high roundhouse", "quietable": 0, "bag": 1, "reversible":1},

    {"name": "Jab, cross, roundhouse", "quietable": 0, "bag": 1, "reversible":1},
    {"name": "Cross, jab, lead roundhouse", "quietable": 0, "bag": 1, "reversible":1},

    {"name": "KB one-handed snatch", "quietable": 1, "kb": 1, "reversible":1},
    {"name": "KB one-handed swing", "quietable": 1, "kb": 1, "reversible":1},
    {"name": "KB alternating one-handed swing", "quietable": 1, "kb": 1, "reversible":0},
    {"name": "KB one-handed clean", "quietable": 1, "kb": 1, "reversible":1},
    {"name": "KB one-handed thruster", "quietable": 1, "kb": 1, "reversible":1},
    {"name": "KB one-handed swing high pull", "quietable": 1, "kb": 1, "reversible":1},
    {"name": "KB swings", "quietable": 1, "kb": 1, "reversible":0, "opener":1},
    {"name": "KB twist press", "quietable": 1, "kb": 1, "reversible":0},
    {"name": "KB deadlift", "quietable": 1, "kb": 1, "reversible":0},
    {"name": "KB standing twist", "quietable": 1, "kb": 1, "reversible":0},
    {"name": "KB Russian twist", "quietable": 1, "ground":1, "kb": 1, "reversible":0},
    {"name": "KB goblet squat", "quietable": 1, "ground":0, "kb": 1, "reversible":0},
    {"name": "KB bob and weave", "quietable": 1, "ground":0, "kb": 1, "reversible":0},
    {"name": "KB squat and press", "quietable": 1, "ground":0, "kb": 1, "reversible":0},
    {"name": "KB reverse lunge and press", "quietable": 1, "ground":0, "kb": 1, "reversible":0},
    {"name": "KB two-handed swings high pull", "quietable": 1, "ground":0, "kb": 1, "reversible":0},
    {"name": "KB lunging one-handed row", "quietable": 1, "ground":0, "kb": 1, "reversible":1},
    {"name": "KB one-handed shoulder press", "quietable": 1, "ground":0, "kb": 1, "reversible":1},
    
    {"name": "BAND: one-handed lateral raise", "quietable": 1, "band": 1, "reversible":1},
    {"name": "BAND: bicep curl", "quietable": 1, "band": 1, "reversible":0},
    {"name": "BAND: front raise", "quietable": 1, "band": 1, "reversible":0},
    {"name": "BAND: palm strikes", "quietable": 1, "band": 1, "reversible":1},
    {"name": "BAND: palm strike situps", "quietable": 1, "band": 1, "ground":1, "reversible":0},
    {"name": "BAND: seated row", "quietable": 1, "band": 1, "ground":1, "reversible":0},
    {"name": "BAND: seated fly", "quietable": 1, "band": 1, "ground":1, "reversible":0},

    {"name": "SPEAR oblique situp", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground side kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground front kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground roundhouse kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground top oblique front kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground bottom oblique front kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground top x-axis shin kick", "quietable": 1, "ground": 1, "reversible":1},
    {"name": "Ground bottom x-axis shin kick", "quietable": 1, "ground": 1, "reversible":1},
    
    {"name": "BOX Thai knees", "quietable": 1, "band": 0, "ground": 0, "reversible":0, "box":1},
    {"name": "BOX jumps", "quietable": 1, "band": 0, "ground": 0, "reversible":0, "box":1},
    {"name": "BOX pushups", "quietable": 1, "band": 0, "ground": 1, "reversible":0, "box":1},
    {"name": "BOX dips", "quietable": 1, "band": 0, "ground": 1, "reversible":0, "box":1},
    {"name": "BOX burpees", "quietable": 1, "band": 0, "ground": 0, "reversible":0, "box":1},

    {"name": "BALL squat press", "quietable": 1, "ground": 0, "reversible":0, "ball":1},
    {"name": "BALL pushups", "quietable": 1, "ground": 1, "reversible":0, "ball":1},
    {"name": "BALL burpees", "quietable": 1, "ground": 0, "reversible":0, "ball":1},
    {"name": "BALL tricep extensions", "quietable": 1, "ground": 0, "reversible":0, "ball":1},
    {"name": "BALL standing twist", "quietable": 1, "ground": 0, "reversible":0, "ball":1},
    {"name": "BALL V-ups", "quietable": 1, "ground": 1, "reversible":0, "ball":1},
    {"name": "BALL twists", "quietable": 1, "ground": 1, "reversible":0, "ball":1},
    {"name": "BALL plank", "quietable": 1, "ground": 1, "reversible":0, "ball":1},

    {"name": "Ground & pound", "quietable": 0, "ground": 1, "reversible":0, "ball":0},
    {"name": "DL GROUND Jab, cross, hook, over", "quietable": 0, "ground": 1, "reversible":0, "ball":0},
    {"name": "DL GROUND Jab, hammer", "quietable": 0, "ground": 1, "reversible":0, "ball":0},
    {"name": "DL GROUND Jab, hammer, hammer", "quietable": 0, "ground": 1, "reversible":0, "ball":0},
    {"name": "DL GROUND Jab, hammer, hammer, outer hammer", "quietable": 0, "ground": 1, "reversible":0, "ball":0}
]